#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.C28_large{1,0,20.2,5
#
Lab2Idle.x28L: package/cfg/Lab2Idle.x28L.mak

clean::
	-$(RM) package/cfg/Lab2Idle.x28L.mak
